### ISSUE TITLE
Error after updating to pandas commit.

### ISSUE THREAD

**Issue by vanguardanon1029** [m-bain/whisperX#42]
I keep getting this error after the new commit to Pandas: 

  File "//whisper.py", line 47, in whisper
    result_aligned = whisperx.align(segments, model_a, metadata, audio_file, device)
  File "/usr/local/lib/python3.9/site-packages/whisperx/alignment.py", line 309, in align
    word_segments_arr["segment-text-start"] = per_word_grp["level_1"].min().reset_index()["level_1"]
  File "/usr/local/lib/python3.9/site-packages/pandas/core/groupby/generic.py", line 1416, in __getitem__
    return super().__getitem__(key)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/base.py", line 248, in __getitem__
    raise KeyError(f"Column not found: {key}")
KeyError: 'Column not found: level_1'

**Comment by vanguardanon1029** [comment]
My exact same script running the previous commit before Pandas update works still.

**Comment by sawadata** [comment]
This wav reproduces the error.
https://huggingface.co/speechbrain/asr-crdnn-rnnlm-librispeech/resolve/main/example.wav
Using pandas 1.5.3.

**Comment by m-bain** [comment]
Thank you, reverted to old commit in default branch now. I will work on these experimental changes till its working fully

**Comment by sawadata** [comment]
https://github.com/m-bain/whisperX/blob/7f2159a9538a4515ac1880ef91dd74a53fd0f633/whisperx/alignment.py#L293
I added `group_keys=True` to this line like this:
`per_seg_grp = char_segments_arr.groupby(["segment-idx", "subsegment-idx"], as_index = False, group_keys=True)`
And the error disappeared.

**Comment by m-bain** [comment]
@sawadata  thank you!
Hmm should work now https://github.com/m-bain/whisperX/commit/5b8c8a7bd39eff6715a3a3a0498d7774f832d205
Let me know

**Comment by sawadata** [comment]
@m-bain
Thank you for your correction.
I tried the latest version.
Unfortunately the exception still reproduces.
May be because 'level_1' is remaining?

```
(venv) ai-ubuntu@ai-ubuntu:~/git/tmp/whisperx$ whisperx --language=en example.wav
Performing transcription...
[00:00.000 --> 00:03.280]  The birch canoe slid on the smooth planks.
Performing alignment...
/home/ai-ubuntu/git/tmp/whisperx/venv/lib/python3.8/site-packages/whisperx/alignment.py:294: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use 

	>>> .groupby(..., group_keys=True)
  char_segments_arr = per_seg_grp.apply(lambda x: x.reset_index(drop = True)).reset_index()
Traceback (most recent call last):
  File "/home/ai-ubuntu/git/tmp/whisperx/venv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3802, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'level_1'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ai-ubuntu/git/tmp/whisperx/venv/bin/whisperx", line 11, in <module>
    load_entry_point('whisperx==1.0', 'console_scripts', 'whisperx')()
  File "/home/ai-ubuntu/git/tmp/whisperx/venv/lib/python3.8/site-packages/whisperx/transcribe.py", line 470, in cli
    result_aligned = align(result["segments"], align_model, align_metadata, audio_path, device,
  File "/home/ai-ubuntu/git/tmp/whisperx/venv/lib/python3.8/site-packages/whisperx/alignment.py", line 384, in align
    cseg['segment-text-start'] = cseg['level_1']
  File "/home/ai-ubuntu/git/tmp/whisperx/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 3807, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/ai-ubuntu/git/tmp/whisperx/venv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: 'level_1'
```

**Comment by m-bain** [comment]
Same issue as in https://github.com/m-bain/whisperX/issues/49
This is because you are running on very short audio file. I will fix this bug when I have time but for now just use longer audio (its not really designed for 3s audio anyway)

**Comment by arnavmehta7** [comment]
@m-bain I am still getting this error. I supplied a 30seconds audio
